name: Publish Docker Image
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" #!....................... タグが「1.0.0」といった形式であること
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        with:
          username: ${{ github.actor }} #!.............. GitHub Action 実行アカウント
#         username: lsmshseslrmuplpjssdjomodjoli #!.............. GitHub Action 実行アカウント
#         password: ${{ secrets.GITHUB_TOKEN }} #!...... GitHub Packages へアクセスするための TOKEN
          password: ${ ACCESS_TOKEN } #!............... GitHub Packages へアクセスするための TOKEN
#         registry: docker.pkg.github.com #!............ GitHub Packages 上のレジストリ
          registry: ghcr.io #!............ GitHub Packages 上のレジストリ
          repository: ${{ github.repository }}/hello #!. Dockerイメージの名称
          tag_with_ref: true #!......................... タグが「1.0.0」である制限を有効にする

